using System.Windows.Forms;

namespace ElsClockStrikes.Core
{
    public class HotKeySet
    {
        public enum KeySet
        {
            None = Keys.None,
            A = Keys.A,
            B = Keys.B,
            C = Keys.C,
            D = Keys.D,
            E = Keys.E,
            F = Keys.F,
            G = Keys.G,
            H = Keys.H,
            I = Keys.I,
            J = Keys.J,
            K = Keys.K,
            L = Keys.L,
            M = Keys.M,
            N = Keys.N,
            O = Keys.O,
            P = Keys.P,
            Q = Keys.Q,
            R = Keys.R,
            S = Keys.S,
            T = Keys.T,
            U = Keys.U,
            V = Keys.V,
            W = Keys.W,
            X = Keys.X,
            Y = Keys.Y,
            Z = Keys.Z,
            F1 = Keys.F1,
            F2 = Keys.F2,
            F3 = Keys.F3,
            F4 = Keys.F4,
            F5 = Keys.F5,
            F6 = Keys.F6,
            F7 = Keys.F7,
            F8 = Keys.F8,
            F9 = Keys.F9,
            F10 = Keys.F10,
            F11 = Keys.F11,
            F12 = Keys.F12,
            Ctrl = Keys.LControlKey,
            主鍵盤0 = Keys.D0,
            主鍵盤1 = Keys.D1,
            主鍵盤2 = Keys.D2,
            主鍵盤3 = Keys.D3,
            主鍵盤4 = Keys.D4,
            主鍵盤5 = Keys.D5,
            主鍵盤6 = Keys.D6,
            主鍵盤7 = Keys.D7,
            主鍵盤8 = Keys.D8,
            主鍵盤9 = Keys.D9,
            小鍵盤0 = Keys.NumPad0,
            小鍵盤1 = Keys.NumPad1,
            小鍵盤2 = Keys.NumPad2,
            小鍵盤3 = Keys.NumPad3,
            小鍵盤4 = Keys.NumPad4,
            小鍵盤5 = Keys.NumPad5,
            小鍵盤6 = Keys.NumPad6,
            小鍵盤7 = Keys.NumPad7,
            小鍵盤8 = Keys.NumPad8,
            小鍵盤9 = Keys.NumPad9
        }
    }
}
